% 히스토그램 그래프
figure('Position', [100, 100, 800, 400]);

% 구간 수를 50개로 설정한 히스토그램
histogram(ber_values_1, 50, 'Normalization', 'probability', ...
    'FaceColor', [0.3010 0.7450 0.9330], 'FaceAlpha', 0.3, ...
    'DisplayName', '통상환경');
hold on;
histogram(ber_values_2, 50, 'Normalization', 'probability', ...
    'FaceColor', [0.8500 0.3250 0.0980], 'FaceAlpha', 0.3, ...
    'DisplayName', '잡음환경');

title('BER 분포 히스토그램 (50 구간)');
xlabel('BER 값');
ylabel('확률');
grid on;
legend('show');

% 통계량 표시
stats_text = sprintf(['통상환경 - 평균: %.2e, 표준편차: %.2e\n' ...
    '잡음환경 - 평균: %.2e, 표준편차: %.2e'], ...
    mean(ber_values_1), std(ber_values_1), ...
    mean(ber_values_2), std(ber_values_2));
annotation('textbox', [0.15, 0.7, 0.3, 0.2], ...
    'String', stats_text, ...
    'BackgroundColor', 'white', ...
    'EdgeColor', 'black', ...
    'FitBoxToText', 'on');

% 밀도 함수 그래프
figure('Position', [100, 550, 800, 400]);
x_range = linspace(min([ber_values_1, ber_values_2]), max([ber_values_1, ber_values_2]), 100);

pd1 = fitdist(ber_values_1', 'Kernel');
y1 = pdf(pd1, x_range);
plot(x_range, y1, 'LineWidth', 2, 'Color', [0.3010 0.7450 0.9330], ...
    'DisplayName', '통상환경');
hold on;

pd2 = fitdist(ber_values_2', 'Kernel');
y2 = pdf(pd2, x_range);
plot(x_range, y2, 'LineWidth', 2, 'Color', [0.8500 0.3250 0.0980], ...
    'DisplayName', '잡음환경');

title('BER 확률 밀도 함수');
xlabel('BER 값');
ylabel('밀도');
grid on;
legend('show');

% 통계량 표시
stats_text = sprintf(['통상환경 - 평균: %.2e, 표준편차: %.2e\n' ...
    '잡음환경 - 평균: %.2e, 표준편차: %.2e'], ...
    mean(ber_values_1), std(ber_values_1), ...
    mean(ber_values_2), std(ber_values_2));
annotation('textbox', [0.15, 0.7, 0.3, 0.2], ...
    'String', stats_text, ...
    'BackgroundColor', 'white', ...
    'EdgeColor', 'black', ...
    'FitBoxToText', 'on');