function     [OFDM_symbols_Number, Total_OFDM_symbols_Number_that_is_including_Pilot] ...
        = Rx_Step_1_Calculate_OFDM_symbols_Number_and_Total_Number(...
        N, ...
        Whether_NOT_Repetition_coding__OR__Repetition_How_Many, ...
        Fixed_Img_Size, ...
        Modulation_Number, ...
        Subcarrier_Freq_Divided_by)

    int_symbol = bit2int(true(Fixed_Img_Size(1) * Fixed_Img_Size(2) * Whether_NOT_Repetition_coding__OR__Repetition_How_Many, 1), 2);
    PSK_modulated_symbols = pskmod(int_symbol, Modulation_Number, pi/4);

    symbol_length = length(PSK_modulated_symbols);

    OFDM_symbols_Number = symbol_length / (N / (2 * Subcarrier_Freq_Divided_by));

    Total_OFDM_symbols_Number_that_is_including_Pilot = OFDM_symbols_Number + (OFDM_symbols_Number / 4);
end